-- Cost Calculation of Foodr
SELECT
	MEALS.MEAL_ID,
	SUM(MEAL_COST * STOCKED_QUANTITY) AS COST
FROM
	MEALS
	JOIN STOCK ON MEALS.MEAL_ID = STOCK.MEAL_ID
GROUP BY
	MEALS.MEAL_ID 
ORDER BY
	COST DESC
LIMIT
	3;