--Calculating Profit by Bringing Revenue and Cost Togather
WITH
	REVENUE AS (
	--I am bringing my revenue calculation here
		SELECT
			MEALS.MEAL_ID,
			SUM(MEAL_PRICE * ORDER_QUANTITY) AS REVENUE
		FROM
			MEALS
			JOIN ORDERS ON MEALS.MEAL_ID = ORDERS.MEAL_ID
		GROUP BY
			MEALS.MEAL_ID
	),
	--this is my cost calculation
	COST AS (
		SELECT
			MEALS.MEAL_ID,
			SUM(MEAL_COST * STOCKED_QUANTITY) AS COST
		FROM
			MEALS
			JOIN STOCK ON MEALS.MEAL_ID = STOCK.MEAL_ID
		GROUP BY
			MEALS.MEAL_ID
	)
	--this is the profit calculation
SELECT
	REVENUE.MEAL_ID,
	REVENUE,
	COST,
	REVENUE - COST AS PROFIT
FROM
	REVENUE
	JOIN COST ON REVENUE.MEAL_ID = COST.MEAL_ID
ORDER BY
	PROFIT DESC
LIMIT
	3;